### ISSUE TITLE
strange quirk when creating new bosses

### ISSUE THREAD

**Issue by frizzbee30** [kangarko/Boss#1]
Hi, got a very odd quirk when creating a new boss. It doesn't appear to recognise any of the mob types?

Thanks as always   :)

latest version and spigot 1.12.1

![2017-09-05_23 15 09](https://user-images.githubusercontent.com/8957914/30085899-8ed7ec64-9290-11e7-9bd8-16eaf86a9573.png)

**Comment by kangarko** [comment]
Hey,

thank you for reporting. The problem was that the enum was not automatically uppercasing your letters,
and as you may or may not know the EntityType (or all enums in java convention) are uppercased. "CREEPER" will work, but I have "fixed" this in the next release. I am sorry for such trivial issues in an early versions.

You can now close this issue :)

**Comment by frizzbee30** [comment]
Brilliant, no worries and thanks  :)
