### ISSUE TITLE
1.18.2: A lot of bugs

### ISSUE THREAD

**Issue by KorweyKristof** [kangarko/Boss#1012]
Hello! 
I've come to report a ton of bugs. Since I've updated my server to 1.18.2 only like half of the plugin even works.
I can't delete bosses, locations or regions in menus. Bosses don't damage me while I'm in full armor. I can't modify drops.
If I set up a drop and restart the server I just don't get them, it is still in the file, but I don't get the items. Can't use anything with Citizens. The plugin just spits out errors to my console. If I give a boss an enchanted weapon the enchant vanishes. If the boss is set up for riding, after restart the ride disappears.
It's really frustrating, because everything worked in version 1.16.5. I'm using Boss 4.3.2.
[debug.zip](https://github.com/kangarko/Boss/files/8311577/debug.zip)

**Comment by kangarko** [comment]
Thanks!

1. Can't remove bosses/locations/regions.
Patched.

2. Bosses don't damage me while in full armor: 
Can't reproduce: https://i.imgur.com/WY1j4qm.png
I noticed you were using Purpur which we don't officially support, please use Paper to see if this problem goes away.

3. Drops stop working after a restart
Can't reproduce either, possibly because of the above fixes it started to work normally. Let me know if that still happens on Paper with the next version.

4. Can't use anything with Citizens
Enable citizens in Boss > Settings > Citizens: https://i.imgur.com/UJuZv81.png

5. Console errors when setting up player drops
Thanks, patched.

6. Enchanted equipment loses attributes:
Thanks, patched.

7. Ride disappears after restart
Thanks, got it working fine, lemme know if you experience more issues!

Thanks for your patience! The new release will come out in a few hours.
