### ISSUE TITLE
1.18.2: Bosses spawn with no players around

### ISSUE THREAD

**Issue by LucidAPs** [kangarko/Boss#1017]
After you released the version with the 1.18.2 support, this started to happen again https://github.com/kangarko/Boss/issues/991
the only difference is that at least bosses respect the limits set in the config files, but they still spawn even though there are no players around. Please fix it again. 

Also if you could make it so that location spawning doesn't spawn all bosses at the exact same single block, that would be great because it looks really unnatural and strange.

[debug.zip](https://github.com/kangarko/Boss/files/8333460/debug.zip)

**Comment by kangarko** [comment]
Sorry for the delay! Investigating asap

**Comment by kangarko** [comment]
Sorry for the delay! Investigating asap

**Comment by kangarko** [comment]
Have you tried setting Spawning.Location_Spawn_Nearby_Player_Radius to a low number such as 10? It will only spawn the Boss if a player is nearby within 10 blocks around the said location.

Failed spawn rule will show up when you set Debug to "[spawning]" in settings.yml as Not running due to players not in nearby radius (X).

I will add a new option for Location spawn rule called "Offset", randomizing the location.
