### ISSUE TITLE
1.18.2: Automatic Updates?

### ISSUE THREAD

**Issue by LandenMantis** [kangarko/Boss#1051]
Hey. I recently purchased this plugin and have a few questions.

Firstly, Does this plugin update automatically? Or do I need to re-install the plugin to get the newest version? If I were to have to re-install the plugin, would it still save my current bosses.

Secondly, Do I need coding experience to create my own custom boss abilities. I have no idea how i would make them, but I would be very interested in trying. Is there any tutorials to help me with this?

Also, is it possible to allow players without OP permissions to use the boss spawn eggs?

Lastly, This is more of a bug report but I didnt wanna send a seperate message for it. Sometimes when i make a boss ride another mob or boss, and restart the server, the boss or mob that was being ridden dissapears, and the spawn egg is no longer in the riding gui. Is this user error?

Thank you so much for making this plugin. Has been really fun to mess around with.

**Comment by kangarko** [comment]
You need to reinstall it manually, the hassle and the fact we're selling on multiple marketplaces is not worth the effort.

For the most part you can customize bosses using our GUI as promised in the ads, but if you need anything else that's not in the menu, you will need to make a small plugin.

I do have a free trial of my coding class but I think it would be way too much time for you, you can just ask someone to make a tiny addon. But for the most part we do cover a ton of features of bosses in our menus. 

Or, you can install Citizens, which effectivelly connects with Boss and you can then manage your Bosses through Citizens and all of its integrations too, opening another range of possibilities.

Yes, players without OP can still use Boss egg feature, as long as they have these perms: https://github.com/kangarko/Boss/wiki/Permissions#use

Thanks for your bug report, may you please attach your /boss debug in a new issue or in the comment below when it happens again, preferably with the egg that's disappearing so I can test it. Make sure you test using Paper since we had a few forks causing weird glitches.
