### ISSUE TITLE
Paper 1.16.5: Health Limit not compatible with Slimes, Magmas, etc.

### ISSUE THREAD

**Issue by RebelDs** [kangarko/Boss#1062]
Hi. My report will be a short one because this is a problem related to the plugin's mechanics and has been an issue since Boss 3 (at least).

Slimes and Magmas (possibly other mobs) are relatively buggy once we increase their size. This bug is manageable for the most part, but if the health of the mob is set up past 2000 (limit in spigot.yml modified), the boss would still not have the desired HP. This might be because the plugin divides the health of the mob per split (the plugin sometimes still spawns slime/magma splits even though we disabled the option). If we set 2000HP or more, the slime/magma will revert to 144 HP (or some other random values). This problem is specific to mobs where we can increase or decrease the size, since regular mobs can have their HP increased past 2000 with no issue whatsoever.

**Comment by kangarko** [comment]
Thanks, I am sorry however Minecraft has never been designed for such high mob sizes or HP values, what you are seeing are problems with the server culling these values back because of an overflow (or something else, I am not entirely sure). 

Bottom line, this is coming from outside of our control, you need to find balance between these extreme values and stability on your own.
