### ISSUE TITLE
Minecraft Version: 1.20.1

### ISSUE THREAD

**Issue by iZeaoGamer** [kangarko/Boss#1187]
Hey. So the Bosses still lose Ability. But I did do more testing, and all the other entities don't seem to lose AI upon server restarts, only when we use `Citizens`. Not sure why that is, but there's no error to report there is an issue. I just need this solved ASAP if possible. The other entities when spawning never lose AI, only Citizens does. Thank you!

If you want me to send any other information, do let me know! Thank you.

**Comment by kangarko** [comment]
Just to confirm they lose AI you mean the Pathfinder Kill Target and they stop chasing the entity from the Select Target menu?

![a](https://i.imgur.com/hEbJ5eo.png)

Other plugins might cause conflicts too, try with just Boss and Citizens because I just tested and it still works even after /reload and restart (you might want to wait 5-10 seconds before the Boss calculates the target, also make sure the target is within radius)

**Comment by iZeaoGamer** [comment]
This is more abt Player entity type not any other entity. @kangarko

**Comment by iZeaoGamer** [comment]
Since this bug only happens with Player Entities.

**Comment by kangarko** [comment]
Unfortunately player NPCs have special treatment in Citizens. I'll attempt to fix but can't promise anything. We had the same issue with many properties and ended up manually having to inject it to the NPC each time. Due to the complexity it might take a while.
