### ISSUE TITLE
Boss top of Spark during lag.

### ISSUE THREAD

**Issue by sennby** [kangarko/Boss#1239]
https://spark.lucko.me/yxKRYiOunG
Server was having a big lag spike, spark has boss at the top of the list. Curious on how we can improve/prevent this?

**Comment by kangarko** [comment]
Unfortunately CraftRegionAccessor.getLivingEntities() is slow since 1.13+. [I already opened a ticket long time ago and it seemed to get better](https://github.com/PaperMC/Paper/issues/2125), but perhaps what you can do is test it on vanilla Paper and if it is still appearing slow, open another ticket with Paper please.

**Comment by kangarko** [comment]
I just spent the last hour trying to manually count entities in loaded chunks to no avail, I don't think I will be able to move thru this unless upstream optimizes the call.
