### ISSUE TITLE
1.8.8: Lag Spike on Big Spawn Amount

### ISSUE THREAD

**Issue by IceGames23** [kangarko/Boss#1253]
Hello, I'm doing a horde event for my server and for this system I'm using /boss spawn for spawn bosses, but always when I spawn a lot of bosses, 50+ bosses, the server has a big lag spike, frezzing the server for some seconds and flooding console with boss spawn message. I want to know if that issue can be fixed.

**Comment by kangarko** [comment]
Please provide a spark report so we can properly investigate or any deeper reports.

**Comment by kangarko** [comment]
Oh I see. You are on 1.8.8 which does not support persistent boss metadata so we have to write it to a file each time a boss spawns. For better performance use 1.16+ because Spigot added support for native metadata to entities. Unfortunately I dont see an easy way around this. Running it async will produce other issues.

**Comment by kangarko** [comment]
Try the next version, I made a huge performance boost by only saving the metadata file on server stop/reload instead of each time it is used (i.e. each boss spawn)

**Comment by kangarko** [comment]
You can set the Commands.Spawn.Success message to "none" in the localization/messages_en.yml file to disable: https://i.imgur.com/h5Z72HJ.png

Yes, as a golden standard all of our plugins will work on Minecraft 1.7.10+!
