### ISSUE TITLE
Feature Requests - New Mobs, Head Features, Chat function

### ISSUE THREAD

**Issue by reneg1990** [kangarko/Boss#14]
Heyo.
Been messing around more with the plugin and absolutely love how it all works so far!

I have a few suggestions for what id personally like to see added in the near future:

1: More Mob/animal types we can use for bosses (Maybe even add a disguise function so we can change mob behaviour, similiar to how mythicmobs does it). I'd really like to see Snowmen added ASAP, as Christmas is right around the corner, and i have some good ideas for events using Boss.

2: Ability to use PlayerHeads in the Hat slot when you gear your monsters. This would allow us to "customize" things a bit more.

3: Have chat messages a boss can use during a fight, maybe even have it say it at %HP values? A lot of our players loved our old mobs to kinda "trash" talk people during fights etc, so i think thatd make it way more emersive.

4: Possibility to set Amount of Mob Spawns in a region we create with the Boss Plugin.
- Im trying to make MMO monster camps basically, and it'd be super neat if i have more control of what spawns at a specific interval in certain areas etc.

Kind regards, Rene :)

**Comment by ElementalShadow** [comment]
Good idea specially Idea 2. kangarko said that is possible but that is not possible.
http://prntscr.com/gxku39

**Comment by kangarko** [comment]
Hey!

**1. More Mob Types**
Snowmen is awesome! I will be adding it soon. No disguise function for us here, because Boss doesn't dig into NMS and it's aimed to be easier then MythicBoss, ultimately having a few limitations in favour of great performance and stability.

**2. Player heads**
Just added in the recent update :)

**3. Boss Chatting During Fight**
Great idea, noted right away!

**4. Mob Spawn Control in Boss Regions**
Good idea, but currently my table is very full. I have noted this however, I can't give you an eta :)

**Comment by reneg1990** [comment]
Thanks for getting back to me regarding all of this Kangarko!
- I understand the logic behind the Disguises, and thats completely fine tbh. i think the ease of use makes up for it defenitly.

Regarding 4, not sure what your thoughts are on that one, I'd say it might be a good "priority" to look into though. I know a lot of us whos using MythicMobs purely use it because of the fact we can make "spawn areas" and control how many mobs should be alive at certain times and what not. I think it might be worth looking into :D As someone whos making adventure maps thats meant to be for multiple people etc, this is probably the last feature that we're really needing.
