### ISSUE TITLE
Bosses that pick up player items do not drop on death.

### ISSUE THREAD

**Issue by Leomelonseeds** [kangarko/Boss#146]
Again, title explains it. A boss, for example zombie that can pick up player items do not drop them when you kill them. I'm thinking maybe the lightning destroys them?

**Comment by kangarko** [comment]
This is intended, as Bosses do have custom equipment on them. However, due to a bug in the recent version, neither that was dropped correctly. This is now fixed. If you set an equipment to a Boss, you can configure its drop chances in the menu.

To the next version, I added an option to remove or remain the natural drops (that cover the gained items).
