### ISSUE TITLE
Extensive Resource Usage

### ISSUE THREAD

**Issue by ElementalShadow** [kangarko/Boss#15]
Plugin Boss which I buyed is great but plugin is using 84% of my CPU and that is too much. Please give me refund.

**Comment by kangarko** [comment]
Hey,

I am sorry you're having issues! I can refund you, but please provide me any data from where you know that such usage is present, i.e. a /timings report or anything. How did you find that out?

**Comment by ElementalShadow** [comment]
![2017-10-18_19 13 41](https://user-images.githubusercontent.com/32802268/31732525-1894b850-b439-11e7-87a3-d6fb8a904910.png)
I am using plugin TopLite, Boss plugin is Awesome but that CPU usage is problem, if you think that you can fix that with update or something I will wait.

**Comment by ElementalShadow** [comment]
Now 91%

**Comment by ElementalShadow** [comment]
Link of expirebox: https://expirebox.com/download/c68355cdc6f952800082c13e129e5c07.html

**Comment by kangarko** [comment]
Okay, from my testing, I was not able to reproduce the issue.

If you wish a refund, please PM me on Spigot with the transaction ID please.

Or, lastly, you can just close your eye over that statistic - I believe that it is false, because such high numbers are not even achievable - your server would be unplayable. In my opinion it is a miscalculation in that plugin; but you have a 100% refund warranty so I am going to refund you.

**Comment by ElementalShadow** [comment]
How to get transaction ID?

**Comment by kangarko** [comment]
Go to your paypal, find the payment to Spigot, open up Transaction details and then you'll see it.

Don't post it here, PM me it on Spigot for privacy.

**Comment by ElementalShadow** [comment]
Sended on spigot
