### ISSUE TITLE
Bosses having issues following players on snow

### ISSUE THREAD

**Issue by ElFlyGod** [kangarko/Boss#173]
The bosses do not follow players properly, oftenly stop slow down or do weird turns on snow slab blocks 

(im talking about this kind of snow for the record) https://gyazo.com/8eaee72928313b7a92e382ebe04586fc

**Comment by ElFlyGod** [comment]
Heres a gif of the issue https://gyazo.com/03c5efd1ec86de53c5952c36694d90d8

**Comment by kangarko** [comment]
Hello,

if you are using TacoSpigot for MC 1.8.8, please know that the AI has been improved massively since than.

Boss does not modify the AI (behaviour) of Bosses in any way, shape or form (https://github.com/kangarko/Boss/wiki/Common-Issues#can-you-make-animals-aggressive--add-better-ai), so anything related to how they walk is purely coded in your Minecraft server.
