### ISSUE TITLE
Boss' skills & sounds

### ISSUE THREAD

**Issue by Asteroz** [kangarko/Boss#220]
I'm trying to set a skill on a boss, seems like none of the skills are actually working. Like for ignite, the boss isn't setting players on fire. I'm using Paper 1.13.

Also, debugging or changing of sounds doesn't seem to be working.

**Comment by kangarko** [comment]
Update to 1.13.2. Sorry but for me the skills are working correctly.

![a](https://i.imgur.com/yLi7j9Z.png)

In the next version, please set "Debug" to "[skills]" to see if such console messages appear. Also make sure you do not have god mode.

You should also be able to see "Skipping skill" message when the skill is not applied (each second). Make sure to test with only 1 boss otherwise it will get spammy.

For the sounds problem, update protocollib to http://ci.dmulloy2.net/job/ProtocolLib/422/
