### ISSUE TITLE
Server thread dump, crashing the server. *IMPORTANT*

### ISSUE THREAD

**Issue by Asteroz** [kangarko/Boss#225]
This is my full server thread dump error - https://hastebin.com/pasiwihubu.md

After further investigation with some people, we believe the root cause is this line; Paper Watchdog Thread/ERROR]:         me.kangarko.boss.final. .a.protected(SourceFile:923)

Seems like, the issue is that the plugin is loading and accessing the chunk map async (and using methods which are NOT safe to call async), in the network thread, which means that that is an easy area to trigger a deadlock.

**Comment by kangarko** [comment]
@jascotty2

**Comment by jascotty2** [comment]
This issue appears to be linked with how the boss handler was created to deal with remapping sounds using ProtocolLib. Instead of maintaining a list of active boss entitiy objects, it calls calls the world to check the entity that caused the sound, but sounds packets are async and the world is in a single thread. :/
A temporary workaround would be to disable ProtocolLib until we get this worked out (sorry about that)

**Comment by Asteroz** [comment]
> This issue appears to be linked with how the boss handler was created to deal with remapping sounds using ProtocolLib. Instead of maintaining a list of active boss entitiy objects, it calls calls the world to check the entity that caused the sound, but sounds packets are async and the world is in a single thread. :/
> A temporary workaround would be to disable ProtocolLib until we get this worked out (sorry about that)

Is it possible to just disable ProtocolLib for the Boss plugin?

**Comment by kangarko** [comment]
@Asteroz I added this option. New release will be available today. If you will still have crashes, please let me know below.
