### ISSUE TITLE
Questions before I buy

### ISSUE THREAD

**Issue by Disorbs** [kangarko/Boss#263]
Got some questions about it before purchasing

1.) Does it support rewards based on damage ? if so does it support priority's like if you reward for 5% dmg and then 10% dmg can you choose not to give the lower version?
2.) does it support chances per skill and not have a overall chance like if i want a skill to happen 10% chance and another at 90%?

**Comment by kangarko** [comment]
Hey, unfortunately at this time both features are not available.

We support direct inventory drop so you can give players the reward directly to their inventory instead of dropping on the floor. You can configure the following options:

![a](https://i.imgur.com/K4fDc0e.gif)

Skills work a bit different, there is no chance but a time delay between which the skill occurs randomly. This can be currently configured flat per every Boss.
