### ISSUE TITLE
Enable unloaded chunks butcher

### ISSUE THREAD

**Issue by x1p** [kangarko/Boss#264]
The butcher command works fine although it only kills mobs in active chunks. The chunks that are not active are not butchered. They don't despawn upon unload. This leaves large amounts of mobs alive, long after Boss has been removed.

Is there a way to get rid of all boss mobs in all chunks of the whole wide world, active or non-active chunks?

**Comment by x1p** [comment]
So far, I removed > 220 mobs after deactivation of Boss a few months ago. Our limit was 180 during the active time of the plugin. This leads me to conclude that the global limit as provided in the settings is only for activated chunks.

**Comment by kangarko** [comment]
Yes, currently the butcher feature only scans active chunks. We have offline chunks feature in Winter but this is resource intensive, locks down the server and can take hours to complete. It is not efficient to add in this stage for Boss, but works well for Winter for global snow coverage.

Yes, the global limit only accounts for active chunks. Scanning offline chunks each time would freeze the server due to the above and keeping some statistics would be inaccurate and also very resource intensive.

I am leaving this open to enable Butcher to scan chunks offline.

**Comment by x1p** [comment]
> this is resource intensive
Imaging flying over a big Survival world and constantly entering commands to butcher them all :-)

If a plugin would exist to slowly scan the world I could schedule a repetitive job.

**Comment by kangarko** [comment]
Sure, these are all great ideas. When I am not pressured on time I'll take a look.

**Comment by BoosterBots** [comment]
Looks like I am running into this issue as well. I disabled the custom bosses in my world because people were not liking the difficulty now I have them scattered all over the place in my resource world :\ I tried everything from disabling the plugin to flying around buttchering them and they are still killing new players by the hour :( any help here would be appreciated.

**Comment by kangarko** [comment]
Thanks, this has been suggested multiple times so I increased its priority and it will be added into the next release :)
