### ISSUE TITLE
Different amounts of bosses spawning

### ISSUE THREAD

**Issue by Kiluminator** [kangarko/Boss#307]
I have some Bosses I want to spawn additionally to the default Vanilla monsters at night. Therefore I would use timed spawning, right?
Is it possible to have some Bosses spawn more often that others (It seems to me that the timed spawn settings in settings.yml affect all bosses the same)?
So basically I want a certain boss to be spawning often and another one to be quite rare and one to be super rare and so on...

edit: I don't quite understand how the timed spawnings, which seem to be limited by the maximum limit of bosses per chunk (?), and the chances you give your boss per world in the in-game GUI work together...

**Comment by kangarko** [comment]
Hi!

Yes, you can use timed spawning and add conditions so the Boss only appears during night time.

Yes, it is possible so that some bosses spawn more frequently, increase their world spawn chances in the Spawning menu.

Just enable timed spawning and configure the spawning rates in the GUI in-game. You can always increase the max amount of Bosses per chunk in "Limits" in settings.yml
