### ISSUE TITLE
I can't spawn boss with spawner

### ISSUE THREAD

**Issue by Rasiorz** [kangarko/Boss#357]
I have do all the way with (boss / worldguard / residence) but mobs not spawn at the spawner area

question 2 : If i want to make when player kill mobs it's will be born other mobs at the next level.
such as (player kill 3 slime it's will be born 4 wolf at the next level)
I have use "command on death" but if I kill 1 slime it's will born new that I don't want like that. I want to kill 3 slime to born other mobs at next level.

Thank you for your reply <3

**Comment by mafia1156** [comment]
This is my config file and my boss that i want to spawn

[boss.zip](https://github.com/kangarko/Boss/files/3357276/boss.zip)

[Other info]
Minecraft version 1.12.2
Boss v.3.3.5-v.3.3.6 [I not sure 3.3.5 or 3.3.6]

[Other problem report]
In spawner I can't choose boss egg at spawner GUI I not sure it's will effect my spawner ?

[Other request]
Is it possible to change size of boss that I want because I can change with Slime but other mobs can't change

**Comment by kangarko** [comment]
Hey, I apology so much for overseeing this ticket! A lot of has changed since the release you speak of, including a fix for the boss egg spawner GUI.

I am closing this in good faith that the latest release (we have another big one coming tonight) provides a fix for your issues. If not just write below and I see your message.

PS: Sadly it is not possible to change Boss sizes due to Minecraft constraints.
