### ISSUE TITLE
Feature Request: Custom AI for a specific mob, The Giant, or the ability to set an AI for mobs that don't have an AI.

### ISSUE THREAD

**Issue by DXUltimate** [kangarko/Boss#366]
So, this feature request could turn into a mega project, but I wanted to leave this open since you're very open about everything submitted here, and on spigot.

The Giant, is pretty much an empty shell that has been left in the mc code for god knows how long. I know completely changing a mob's AI would be a nightmare as you mentioned in previous issue posts, but what about being able to set certain AI selectors to mobs that don't have an AI, aka, making the giant hostile (as it should have been ever since they removed it's AI for it), or even passive/friendly. Wouldn't assigning it an already existing regular zombie AI be significantly easier than trying to write a brand new cloned hostile AI for it? Just food for thought.

Consider this, either having an extension plugin for Boss, that would allow everyone without the configuration knowledge, or coding knowledge, to set up the artificial intelligence as a custom AI just like how Boss is set up for changing, health, drops, armour, etc, or a total integration of this feature in the plugin itself since it has been requested quite a bit since the start of this plugins life (looking at both all of githubs and spigots reviews, suggestions, discussion, etc.

As always, keep it up with this plugin. I will always use it. =D

**Comment by kangarko** [comment]
Hi,

although I am generally open that that, I had to stop taking suggestions due to a) some stability issues and b) very limited time due to recording training courses for Minecraft.

For now this is the main reason we are not tampering with AI: https://github.com/kangarko/Boss/wiki/Frequent-Questions-and-Tips#can-you-make-animals-aggressive--add-better-ai

However, we are planning to use the Citizens plugin to alter the AI and once that is prepared then this will also include the Giant mob :)

Thanks
Matej
