### ISSUE TITLE
Handle Boss Spawners using our rules, not vanilla

### ISSUE THREAD

**Issue by BobbyMere** [kangarko/Boss#411]
I can't get slime spawners to works even though other spawners do. Is there a way to get them to work even without them being in a slime chunk?

**Comment by kangarko** [comment]
Hey there!

Thanks for using Boss. I am afraid that's a hard wall, since we rely on the vanilla rules to spawn the monsters. Such as that Zombie Spawners require Night, it may as well be that the Slime Spawners will require the slime chunk or some other condition - I am honestly not aware of which.

Sorry for that!

Good news is that if we happen to rewrite our system we can take over the spawning mechanics completely, so I am leaving this on for a future implementation.

**Comment by kangarko** [comment]
Will be implemented.
