### ISSUE TITLE
Two Questions before Purchasing

### ISSUE THREAD

**Issue by BuildABeastWorkshop** [kangarko/Boss#422]
Hi, I found your plugin recently and I'm wondering if I might prefer to use Boss over MythicMobs for my server. I just have a couple of questions regarding functionality before I make my purchase. The fact that this plugin has a GUI editor is a very big selling point for me, but I need to make sure all the features I need to achieve the level of quality I want are there. First, your section on skills mentions that developers may add entirely new skills using your API. How much prior knowledge with Spigot development in general would I need to be able to accomplish this? I've done quite a bit of programming, and I did modding for a few years, but I have zero experience developing plugins, and it sounds like you can't add new skills using the in-game editor. I want to make sure my bosses look and feel unique, and based on the list of skills that come with the plugin, it seems that I would have to add new skills for custom attacks with particle effects and the like. Secondly, MythicMobs interacts with LibsDisguises in order to make any mob look like any mob; for example, you could have a squid that behaves like a blaze, or a snow golem that behaves like a zombie. Is there any analagous feature for Boss? How easy is it to implement? Thank you for your time.

**Comment by kangarko** [comment]
Hey,

thanks for your interest. You need to have at least basic understanding of Java/spigot to add new skills but good news is we rolled an education platform that teaches you that, as a part of its free trials: mineacademy.org

Tutorial on adding skills here: https://github.com/kangarko/Boss/wiki/Developer-API

Second, there is no such feature for Boss right now, as we aim to keep the plugin as clean and error-free as possible. Intercepting with packets and NMS turned out to be problematic so we decided not to include it. Feel free to use both plugins if you'd like.

Let me know if you got any more questions.

-Matej

**Comment by kangarko** [comment]
Closing, let me know below if more questions
