### ISSUE TITLE
Bosses with the player teleport skill don't check for Citizen NPCs

### ISSUE THREAD

**Issue by TheWasabiDude** [kangarko/Boss#473]
Greetings. Citizen is a widely used and liked NPC managing plugin, that I also use on my server aside your boss plugin.

Today I noticed that if a boss with the player teleporting ability gets near enough to them, it will also teleport the NPC to itself.

I went on their discord and asked about how to solve this and they said it's your plugins' fault, as their API has checks to see if a target is their NPC so the teleport won't affect them.

Can we get support for this? It's really annoying that these bosses keep teleporting my leaderboard NPCs

**Comment by kangarko** [comment]
It's not entirely Boss fault because Citizens injects player entities into Bukkit. Boss only calls native Bukkit API which thinks that there are indeed living players online. I communicated this to their dev team but they refused to do anything about it due to works involved.

I have added a special check for Citizens when we are targeting players in Boss skills though :)
