### ISSUE TITLE
Spawning Natural Boss

### ISSUE THREAD

**Issue by LegendSpard4** [kangarko/Boss#482]
I just selected a region for the appearance of bosses automatically but it seems that it does not work

**Comment by LegendSpard4** [comment]
is activated but no boss appears as it should

**Comment by LegendSpard4** [comment]
https://i.imgur.com/ZDnwDU4.png

**Comment by kangarko** [comment]
Please ZIP me your Boss folder.

**Comment by LegendSpard4** [comment]
here it is https://www.mediafire.com/file/jddp0gdo45msyyc/Boss.rar/file

**Comment by LegendSpard4** [comment]
> Please ZIP me your Boss folder.

help me pls

**Comment by kangarko** [comment]
From your settings only the Pancayo boss should appear in the spawnboss region. Your Timed_Spawning.Delay in settings.yml is on 90 seconds, so that means the Boss will try to spawn every 90th second. It only does spawn in worlds named "world", "world_nether" and "world_the_end", check that you are on the right world.

If it still does not spawn in the region, please read https://github.com/kangarko/Boss/wiki/Common-Issues#bosses-are-not-spawning-naturally and set the Debug option as described there, then post me the console output. Thank you.

**Comment by lackoSK** [comment]
Closing this issue, the author of it is not responding to us.
