### ISSUE TITLE
Spider Spawner Problem

### ISSUE THREAD

**Issue by BobbyMere** [kangarko/Boss#516]
Using v3.6.8 on paper spigot 1.13.2 

Using two boss spawners, one with a cavespider and the other using a normal spider, the mob cap of both spawners overlap each other. 

A mob cap of 1 for the normal spider spawner will be effect by mobs spawned by cavespider spawner. 

Having 5 cavespiders in an area where the mob cap of 1 for the normal spider spawner, the normal spider spawner will never activate as the cavespider for some reason acts as if both the normal spider and cavespider have the same id, regardless if both spawners are different types of mobs and different names assigned to them. 

Djieien (normal spider) will not spawn with a cap of 1 if
Djieien Minion  (cavespider) is in the area

[Boss.zip](https://github.com/kangarko/Boss/files/4227773/Boss.zip)

**Comment by JavaFactoryDev** [comment]
Hi BobbyMere,

thank you for reporting this issue,

I will have a look soon.

Regards,
- Leonhard from MineAcademy

**Comment by BobbyMere** [comment]
Any update?

**Comment by JavaFactoryDev** [comment]
Sorry for the delay. 
This issue was pretty weird and required a lot of testing.

I, first of all, tried to find an issue on the mob-detection, but there wasn't one.

After a lot of testing, I found out that cave spiders were threatened as spiders in bukkit.
This also enables me to fix this issue.

This issue will be fixed until the next release.

Regards,
- Leonhard from MineAcademy

**Comment by JavaFactoryDev** [comment]
Btw can you try setting Iterate_Spawning_Tries to true, please?

**Comment by JavaFactoryDev** [comment]
User doesn't respond.
