### ISSUE TITLE
Boss helmets vanish

### ISSUE THREAD

**Issue by bc-hill** [kangarko/Boss#54]
Make a boss, and equip it with a helmet.  Stand around for 15 minutes or so, and the helmet is gone.  
Add or remove a helmet from any other boss, and all bosses' helmets are visible again.
Does not occur with any other equipment on boss.
Boss 1.5.10. Let me know if you need more info.

**Comment by kangarko** [comment]
Hey, sorry for the delay, could you please do a quick testing:

* Test this in an outside arena where direct sunlight shines on the Boss.
* Test this in a cave / under a roof where the mob wouldn't burn (regardless of their Boss' settings).

**Comment by bc-hill** [comment]
Confirmed!  This appears to only happen when the boss is exposed to sunlight.

Testing this also made me notice that they still seem to be avoiding the sunlight, even if they are not burning.  For example, the skeletons were trying to stay right next to the cliff, where the light levels were lower.  And it worked out for them.  They didn't lose their helmets until I made them move away, and installed a fence.

**Comment by kangarko** [comment]
Thanks for testing, I will fix this in 24h.

On the latter - this is caused by a digged-deep-inside pathfinder in Minecraft server. Boss is and won't manipulate those.

I can also try giving them invulnerable helmets, and make it so when such helmet is drop, the invulnerability is lost. Sounds good? // Haven't tested yet.

**Comment by kangarko** [comment]
@bc-hill sorry for the delay! I unfortunately missed it due to works on ChatControl but getting back to you right now.

I cannot reproduce on 1.12.2, what's your Minecraft versions? Skeletons won't run away from sunlight on my server either -> Do they run after you add a helmet and they are spawned already, or you already spawn them with a helmet on?

**Comment by kangarko** [comment]
Closing, assuming fixed.
