### ISSUE TITLE
1.15.2: Console spam + error on respawn

### ISSUE THREAD

**Issue by TwerkRekt** [kangarko/Boss#592]
Hello!

plugin version: 3.8.4
server version: paper 1.15.2

I have a issue, when player is killed by any boss he  respawn at last location and not in the spawn
and console spam it
https://pastebin.com/wZ8UAjDK

**Comment by AngellitoX** [comment]
Hello, by looking at your logs, it appears you're using SSSpigot which seems to an unsupported fork. Before any further procedure, can you please test if this happens when using Spigot or Paper official forks and let us know?

Also if it helps, please share your Boss settings so we can also take a look into it.

Thank you!
Angel from MineAcademy

**Comment by kangarko** [comment]
Thanks, will be fixed in the next release.
