### ISSUE TITLE
1.16.3: Bunch of problem

### ISSUE THREAD

**Issue by jeeshen** [kangarko/Boss#623]
1) Boss loots went to player inventory when the option is disabled

2) Boss equipment getting reset every time i open the menu and the boss will never get equipment

3) Boss still wearing random equipments when it is disabled

May i know what i going on to this plugin? I cant even get support and no one is fixing it

**Comment by kangarko** [comment]
Where can't you get support? This is the official place to get support, there is no nowhere else.

As instructed by the template, you should've sent me your Boss folder as a ZIP uploaded so I can test it using your config.

Also ensure you're on the latest version of Boss as I believe 2. was fixed already.

**Comment by jeeshen** [comment]
oh i see but where is the discord server?
[Desktop.zip](https://github.com/kangarko/Boss/files/5232507/Desktop.zip)

1 is fixed but 2 wasnt fix

**Comment by kangarko** [comment]
Thanks

There is no public Discord for the time being, that does not mean there is no support

**Comment by jeeshen** [comment]
oh? how long does it take to get them fixed?

**Comment by AngellitoX** [comment]
Helllo there! It should be fixed in less than a week basis. Matej (Kangarko) is the only current developer working on all of the MineAcademy products and courses and the workload is extremely heavy for now. I'm sure this will be fixed promptly.

We deeply appreciate your patience and apologize for the inconvenience of not having a Discord server for now.

Angel from MineAcademy.org

**Comment by jeeshen** [comment]
Okay thanks for replying me!

**Comment by kangarko** [comment]
Okay so I had time to test it:

1. Sorry, I cannot reproduce, works fine for me: https://i.imgur.com/GPabTEH.gif

2. Neither this can I reproduce, again works alright for me: https://i.imgur.com/MOgGi5w.gif

3. Yeah there is a small chance of this due to some SpigotMC underlying behavior we cant control.

For 1 and 2, what other plugins are running on your server? Try just having Boss without anything else to see if the issues persist on your 1.16.3. This was my setup: https://i.imgur.com/kNJ87k7.png

**Comment by jeeshen** [comment]
ah it is fixed after i remove the file and regenerate it! Thank you so much!
