### ISSUE TITLE
1.12.2: Spawners don't work after restart

### ISSUE THREAD

**Issue by KickSquareMC** [kangarko/Boss#798]
Hi, I'd like my spawners to spawn bosses. However, when I restart the server, the spawners stop working. Destroying the spawners and placing them back down fixes it, but I can't do that manually every time I restart.

Folder:
[Boss.zip](https://github.com/kangarko/Boss/files/5852386/Boss.zip)

**Comment by kangarko** [comment]
Sorry due to time constrains we cannot offer this issue being resolved for the time being, I recommend you explore alternative spawning options such as the one here: https://github.com/kangarko/Boss/wiki/Frequent-Questions-and-Tips#can-i-spawn-bosses-individually-at-a-certain-time

However if there's any console error log just post it here and I will investigate further

**Comment by SoraShiunin** [comment]
Just commenting that this is also happening with version 3.9.9 on 1.16.4.
