### ISSUE TITLE
Big ussage

### ISSUE THREAD

**Issue by ZappySK** [kangarko/Boss#828]
Hey, what does this mean? What i need to optimalize?
![image](https://user-images.githubusercontent.com/76651966/108841939-d3b25e80-75d8-11eb-9374-506887162c88.png)

**Comment by ZappySK** [comment]
@kangarko help?

**Comment by kangarko** [comment]
SafeRunnable hosts a number of runnable tasks within all of our plugin(s).

So that means there are actually multiple runnables inside of this that /timings cannot see. If you would sum up the other runnables from your timings you could get worse results like that. I already explained it here: https://github.com/kangarko/Boss/issues/815#issuecomment-785809029

However, please check out our Wiki guide in Common Questions on optimizing performance of Boss.
