### ISSUE TITLE
Thank You!

### ISSUE THREAD

**Issue by IAmOrion15** [kangarko/Boss#943]
Thank you kangarko for updating the plugin man! I'm telling you, if you keep up with this, it will become even better than Mythicmobs because it has a GUI making it easier for players for me.  I am just here to say thank you and to keep it up!

PS: If you could add some more abilities, that would sick ;)

**Comment by kangarko** [comment]
Love it, thanks <3 Which abilities? Let me know below!

**Comment by IAmOrion15** [comment]
I mean, when it comes to abilities, the options are endless man! Whatever you could dream of! You could add maybe a dash ability where the mob dashes forward into the player. You could add a charge where they run into a straight line until the hit a wall or a player. You maybe add an ability where the mob stands still and heals some of its health back. Maybe you could even differentiate between magic attacks (like the fireball one) and physical attacks (like a throw, or charge). I plan on using this with MMOitems and those plugins.

Anyways! I’m telling you man, keep up the work on this plugin! It will be one of the best ones out there! Thanks for your time! :)

**Comment by kangarko** [comment]
Thanks for your input! We have a flexible API so all of what you have mentioned can easily be added to Boss. I will prepare video tutorials in the next months for that.

I believe we now strike a lightning effect which should not remove the item, anyhow it will still happen with fireball since Bukkit does not easily let us know why the item was removed and I do not want to add some complex heuristics around it, so that is a wontfix sort of bug.

**Comment by kangarko** [comment]
Thanks for your input! We have a flexible API so all of what you have mentioned can easily be added to Boss. I will prepare video tutorials in the next months for that.

I will look into the bug asap!

**Comment by IAmOrion15** [comment]
Thanks man! Keep up the great work!

**Comment by kangarko** [comment]
Sad news, even though we force bukkit not to remove it, it still does apparently on 1.17.1: https://i.imgur.com/KdfXsXB.png

May be a bug in Paper, I can report this when I have time.
