### ISSUE TITLE
1.16.5: Keep Inside feature for Boss Regions

### ISSUE THREAD

**Issue by RebelDs** [kangarko/Boss#946]
The keep-inside option for the boss region seems to be missing in the 4.0.x update and, in my opinion at least - that makes Boss regions obsolete. 

Can the feature be added back? Together with the ability to teleport mobs back to the center of the region (or, even better, to a selected spot within the region) is the mob attempts to leave it? Right now I fear I might be dealing with runaway mobs or stragglers before long, so I'm reluctant to update from the 3.9.7 version.

**Comment by kangarko** [comment]
Thanks, will schedule to implement in a week or two when I got some time!

**Comment by RebelDs** [comment]
> Thanks, will schedule to implement in a week or two when I got some time!

That would be great. The faster the better !

**Comment by kangarko** [comment]
I've added it for you! You can also select a Boss location where we return the Boss to. If Citizens are installed, we walk the Boss nicely instead of hard teleport.

![a](https://i.imgur.com/d6L07Pw.png)

I'd really appreciate you dropping a review at https://www.trustpilot.com/review/mineacademy.org because we don't have many there. Took me about 4 hours to implement, so I'd be very glad if you'd give a rating!

**Comment by RebelDs** [comment]
Will the new version be pushed out today?

Me and my team are really excited !!

**Comment by kangarko** [comment]
Yes it will! Just need to finish some testing to ensure minimum bugs and will be submitting in the evening.
