### ISSUE TITLE
1.17.1: Bosses respawn on server restart, they have vanilla mob health and no equipment

### ISSUE THREAD

**Issue by ItsDronez** [kangarko/Boss#961]
I created some bosses, spawned them with boss eggs, and fought/killed them for testing. When I restart the server, bosses that I killed respawn with normal vanilla health and no equipment, but they still have their abilities. Even an old boss I deleted which was a snowman named "Yeti" is respawning after restart, and it should be deleted. 

Debug:
[debug.zip](https://github.com/kangarko/Boss/files/7678874/debug.zip)

**Comment by kangarko** [comment]
When you right click your Boss after server restart, does it show this message?

![a](https://i.imgur.com/cdUmgZT.png)

**Comment by kangarko** [comment]
You have StackMob installed, could be because it removes our NBT tag. Can you try without that plugin?

**Comment by kangarko** [comment]
Should be solved in the next release, comment below if not.

**Comment by ItsDronez** [comment]
The issue seems to have gotten worse. I updated the plugin and restarted the server to see this:
![unknown](https://user-images.githubusercontent.com/40131910/146075136-9eb7c7a5-803c-4e4d-8f53-ae3287958c02.png)
:

Is there a way to get this to work without removing stackmob? It's a survival server and many players have stacked animals etc.

**Comment by kangarko** [comment]
We place invisible NBT tags on entities which StackMob removes.

We should however, prevent StackMob from stacking Bosses, please set the Debug key in settings.yml to "[stackmob]" **in the dev version below** and report whether you are seeing "Preventing stacking of" console messages when spawning Bosses that should stack (and whether they stack or not).

[Boss-4.1.2.zip](https://github.com/kangarko/Boss/files/7716787/Boss-4.1.2.zip)

**Comment by kangarko** [comment]
If you killed the Bosses and they have been deregistered in the server, they are removed from the saved chunk data permanently. This is done in the vanilla server. So by typing /stop the loaded chunks are saved and next time you start your server, these entities should not exist.

There are couple of plugins which could cause misbehavior: ViewDistanceTweaks (potentially un/load chunks poorly (??)) ClearLag (should not since it only removes entities but not respawns afaik), Chunky (this one spawns entities in pregenerated chunks as per my research, check it), CoreProtect (this one also respawns entities which if they were Bosses, turn into the broken ones you are seeing, when doing a rollback), SimplePets (this spawns entities (??), check if Bosses are not turned into petrs)

**Comment by ItsDronez** [comment]
I'll try this after work thanks, but I do not want them to stack, I only want 1 boss. One boss spawns and I kill it, on server restart many bosses with low hp and no equipment have filled the room. I tested without stackmob plugin and the issue stops, the issue also happens with rosestacker installed. Do you know of any stacking plugins that work with boss?

**Comment by kangarko** [comment]
Could you open an issue at https://github.com/Nathat23/StackMob-5/issues? I think the author is friendly and will help. You can ping me and I will listen to his suggestions to edit Boss internally to add support for StackMob.

**Comment by ItsDronez** [comment]
I did some more testing. I have removed all plugins that you mentioned. ViewDistanceTweaks, ClearLag, Chunky, CoreProtect, SimplePets, and all mob stacking plugins, and they still respawn/multiply on restart.

**Comment by kangarko** [comment]
Unfortunately then I cannot help you, I believe I have already refunded you (?), if not let me know and I'll do so. No idea why your Bosses are respawning after they are killed but this is not something we have in our plugin.
