### ISSUE TITLE
1.17.1: Bosses throwing players causes false positives with Vulcan anti-cheat

### ISSUE THREAD

**Issue by bipedd** [kangarko/Boss#969]
When bosses throw players it causes my anti-cheat (Vulcan) to trigger the motion (TYPE: G) and jump (TYPE: B) checks. I was told to report this here by a support member who also said that the easiest way for the plugin to fix this is to cancel flags for those checks right after a boss uses abilities like that.

https://user-images.githubusercontent.com/77213949/147178147-a88a12e9-051d-498b-a245-153b582f7829.mp4

**Comment by kangarko** [comment]
To throw players, we simply add them a Vector motion for which we use the standard Bukkit methods. Unfortunately I can't add exceptions for individual anticheats due to a lack of time but you could temporarily lower the Motion check threshold.

In the next version, the developer of Vulcan can add an exception for player having the "ThrownByBoss" metadata, as shown in this code example we will remove it 2 seconds after the throw:
<img width="585" alt="Screenshot 2021-12-23 at 09 25 57" src="https://user-images.githubusercontent.com/1918426/147211285-a69df053-cc17-47ca-9f07-d8d5dfe3f3c2.png">
